
type AddTenant struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

AddTenant := &AddTenant{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type AssociatePaymentInstruments struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

AssociatePaymentInstruments := &AssociatePaymentInstruments{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type AssociatePaymentInstrumentsTemp struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

AssociatePaymentInstrumentsTemp := &AssociatePaymentInstrumentsTemp{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type BLANK struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

BLANK := &BLANK{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type EjariTerminationStatus struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

EjariTerminationStatus := &EjariTerminationStatus{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type GetBouncedCheques struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

GetBouncedCheques := &GetBouncedCheques{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type GetContractData struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

GetContractData := &GetContractData{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type GetContractDataForEjari struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

GetContractDataForEjari := &GetContractDataForEjari{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type GetContractDataForEjariTemp struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

GetContractDataForEjariTemp := &GetContractDataForEjariTemp{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }
type GetContractDataTemp struct{
	orgCode string `json:"orgCode"`
orgID string `json:"orgID"`
emiratesID string `json:"emiratesID"`
customerName string `json:"customerName"`
mobileNumber string `json:"mobileNumber"`
emailID string `json:"emailID"`
visaNo string `json:"visaNo"`
visaExpiryDate string `json:"visaExpiryDate"`
emiratesIDExpiryDate string `json:"emiratesIDExpiryDate"`
authToken string `json:"authToken"`
timestamp string `json:"timestamp"`
authToken string `json:"authToken"`
EIDA string `json:"EIDA"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
orgCode string `json:"orgCode"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
paymentInstruments string `json:"paymentInstruments"`
EIDA string `json:"EIDA"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
ejariTerminationStatus string `json:"ejariTerminationStatus"`
orgCode string `json:"orgCode"`
fromDate string `json:"fromDate"`
toDate string `json:"toDate"`
page string `json:"page"`
page string `json:"page"`
page string `json:"page"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
undefined string `json:"undefined"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
contractID string `json:"contractID"`
orgCode string `json:"orgCode"`
EIDA string `json:"EIDA"`
authToken string `json:"authToken"`
contractID string `json:"contractID"`
 }

GetContractDataTemp := &GetContractDataTemp{	
		orgCode:   sanitize(args[0], "string").(string)
orgID:   sanitize(args[1], "string").(string)
emiratesID:   sanitize(args[2], "string").(string)
customerName:   sanitize(args[3], "string").(string)
mobileNumber:   sanitize(args[4], "string").(string)
emailID:   sanitize(args[5], "string").(string)
visaNo:   sanitize(args[6], "string").(string)
visaExpiryDate:   sanitize(args[7], "string").(string)
emiratesIDExpiryDate:   sanitize(args[8], "string").(string)
authToken:   sanitize(args[9], "string").(string)
timestamp:   sanitize(args[10], "string").(string)
authToken:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
contractID:   sanitize(args[2], "string").(string)
paymentInstruments:   sanitize(args[3], "array").(array)
orgCode:   sanitize(args[4], "string").(string)
authToken:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
paymentInstruments:   sanitize(args[2], "array").(array)
EIDA:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[0], "object").(object)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
ejariTerminationStatus:   sanitize(args[2], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
fromDate:   sanitize(args[1], "string").(string)
toDate:   sanitize(args[2], "string").(string)
page:   sanitize(args[3], "object").(object)
page:   sanitize(args[4], "string").(string)
page:   sanitize(args[5], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
undefined:   sanitize(args[4], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
contractID:   sanitize(args[1], "string").(string)
orgCode:   sanitize(args[0], "string").(string)
EIDA:   sanitize(args[1], "string").(string)
authToken:   sanitize(args[2], "string").(string)
contractID:   sanitize(args[3], "string").(string)
  }