'use strict';

module.exports = {
  User: require('./User'),
  Acquirer: require('./Acquirer'),
  Entity: require('./Entity'),
  Group: require('./Group'),
  Permission: require('./Permission'),
  LogTransaction: require('./LogTransaction'),
  Notifications: require('./Notifications'),
  CommissionTemplate: require('./CommissionTemplate'),
  EmailTemplate: require('./EmailTemplate'),
  ReconAudit: require('./ReconAudit'),
  ReconAuditTransaction: require('./ReconAuditTransaction'),
  WorkingCalendar: require('./WorkingCalendar'),
  TypeData: require('./TypeData'),
  PasswordPolicy: require('./PasswordPolicy'),
  AuditLog: require('./AuditLog'),
  CTSDocument: require('./CTSDocument'),
  Document: require('./Document'),
  PasswordHistory: require('./PasswordHistory'),
  SLAEvent: require('./SLAEvent'),
  ReportsCriteria: require('./ReportsCriteria'),
  APIPayload: require('./APIPayload'),
  LoginAttempts: require('./LoginAttempts'),
  ServerStats: require('./ServerStats'),
  Documents: require('./Documents'),
  TokenLookup: require('./TokenLookup'),
  Consortium: require('./Consortium')
};
