'use strict';

module.exports = {
  User: require('./User'),
  Group: require('./Group'),
  Permission: require('./Permission'),
  LogTransaction: require('./LogTransaction'),
  Notifications: require('./Notifications'),
  CommissionTemplate: require('./CommissionTemplate'),
  EmailTemplate: require('./EmailTemplate'),
  WorkingCalendar: require('./WorkingCalendar'),
  TypeData: require('./TypeData'),
  PasswordPolicy: require('./PasswordPolicy'),
  AuditLog: require('./AuditLog'),
  Document: require('./Document'),
  PasswordHistory: require('./PasswordHistory'),
  ReportsCriteria: require('./ReportsCriteria'),
  APIPayload: require('./APIPayload'),
  LoginAttempts: require('./LoginAttempts'),
  ServerStats: require('./ServerStats'),
  Documents: require('./Documents'),
  TokenLookup: require('./TokenLookup'),
  Consortium: require('./Consortium'),
  EventRegistry: require('./EventRegistry'),
  EventDispatcher: require('./EventDispatcher'),
  DataSource: require('./DataSource'),
  APIDefination: require('./APIDefination'),
  MappingConfig: require('./MappingConfig'),
  NetworkConfig: require('./NetworkConfiguration'),
  Channel: require('./Channel'),
  SmartContract: require('./SmartContract'),
  ConsortiumConfig: require('./ConsortiumConfig'),
  EndpointDefination: require('./EndpointDefination'),
  TableFields: require('./TableFields'),
  APITemplates: require('./APITemplates')
};
