
FROM risingstack/alpine:3.7-v8.10.0-4.8.0
MAINTAINER Avanza Innovations <bilal.mahroof@avanzainnovations.com>

WORKDIR /opt/app-root
COPY package.json .
COPY . .

RUN npm install

USER 1001
EXPOSE 9080

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \ 
  CMD curl -fs http://localhost:9080/health || exit 1

CMD ["node","app"]